CREATE OR REPLACE FUNCTION jsonbd_compression_handler(INTERNAL)
RETURNS COMPRESSION_AM_HANDLER AS 'MODULE_PATHNAME', 'jsonbd_compression_handler'
LANGUAGE C STRICT;

CREATE ACCESS METHOD jsonbd TYPE COMPRESSION HANDLER jsonbd_compression_handler;
